#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://github.com/{name}/{reponame}/
#          searchPaths: exampleservice
#          username: {username}
#          password: {password}
#

server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: /Users/noelvock/Projects/spring-microservices-in-action/config/src/main/resources/config/exampleservice
